Based on https://machinelearningmastery.com/a-gentle-introduction-to-particle-swarm-optimization/

In [1]:
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
def f(x, y):
    return (x - 3.14)**2 + (y - 2.72)**2 + np.sin(3*x + 1.41) + np.sin(4*y - 1.73)

In [5]:
x = np.linspace(0, 5, 100)
y = np.linspace(0, 5, 100)

X, Y = np.meshgrid(x, y)
Z = f(X, Y)

In [9]:
import plotly.graph_objects as pgo

fig = pgo.Figure(
    pgo.Surface(
        x=x,
        y=y,
        z=Z
    )
)
fig.update_layout(
    scene={
        "aspectratio": {"x": 1, "y": 1, "z": 0.5}
    }
)
fig.show()

In [10]:
prng = np.random.RandomState(seed=1234)

In [44]:
def update_pos(X, V, P, G, prng, w, c1, c2):
    r1 = prng.uniform(size=(X0.shape[0], 1))
    r2 = prng.uniform(size=(X0.shape[0], 1))
    
    V = w*V + c1*(P - X)*r1 + c2*(G - X)*r2
    X = X + V
    
    return X, V

In [81]:
def update_best(X, fP, P, G):
    fvals = f(*X.T)
    
    P = P.copy()
    G = G.copy()
    fP = fP.copy()
    
    m = fvals < fP
    P[m] = X[m]
    fP[m] = fvals[m]
    
    G = P[np.argmin(fP, axis=0)]
    return fP, P, G

In [82]:
prng0 = np.random.RandomState(seed=1234)
X0 = prng0.uniform(0, 5, size=(10, 2))
V0 = 0.1*prng0.randn(10, 2)

w = 0.7
c1 = c2 = 0.2

In [83]:
P = X0
fP = f(*P.T)
G = P[np.argmin(fP, axis=0)]

In [84]:
Xs, Vs = [], []
fvals = []

for t in range(20):
    X0, V0 = update(X0, V0, P, G, prng, w, c1, c2)
    fP, P, G = update_best(X1, fP, P, G)
    
    Xs.append(X0)
    Vs.append(V0)
    fvals.append(f(*G))

In [85]:
fvals

[-0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805,
 -0.039975493866288805]

In [78]:
P

array([[0.95759725, 3.11054386],
       [2.1886387 , 3.92679292],
       [3.89987904, 1.36296303],
       [1.38232128, 4.00936089],
       [4.79069677, 4.37966317],
       [1.78908635, 2.50497563],
       [3.41731468, 3.56351013],
       [1.85125377, 2.80598093],
       [2.51541583, 0.06884225],
       [3.86413311, 4.41320595]])

In [86]:
Xs

[array([[1.08971307, 2.9558533 ],
        [2.16837406, 3.86119598],
        [3.91922118, 1.41830692],
        [1.51413643, 3.96243036],
        [4.85825218, 4.19796045],
        [1.7707755 , 2.61087255],
        [3.37753065, 3.5972539 ],
        [1.95601163, 2.91057476],
        [2.60178756, 0.05663309],
        [3.8766044 , 4.38092647]]),
 array([[1.4850455 , 2.90334114],
        [2.19220807, 3.80403697],
        [3.85251317, 1.82298519],
        [1.93839467, 3.85684316],
        [4.88025923, 4.05574449],
        [2.04706283, 2.87295164],
        [3.34968184, 3.62087454],
        [2.29993557, 3.11468089],
        [2.82436782, 0.67626769],
        [3.80934242, 4.21382025]]),
 array([[1.8638627 , 2.89323338],
        [2.42683792, 3.71207808],
        [3.74078404, 2.38422035],
        [2.41541722, 3.74519403],
        [4.81639469, 3.95815803],
        [2.51504802, 3.215273  ],
        [3.33392062, 3.63424279],
        [2.6006036 , 3.28432905],
        [3.01845983, 1.27464617],
        [3