## The 1D case

In [1]:
import torch
import torch.nn.functional as F

In [2]:
x = torch.arange(10.0, 15.0).reshape(1, 1, 5)
w = torch.Tensor([[[1.0, 2.0, -1.0]]])

In [3]:
x.shape

torch.Size([1, 1, 5])

In [4]:
w.shape

torch.Size([1, 1, 3])

In [5]:
F.conv1d(x, w, padding=1)

tensor([[[ 9., 20., 22., 24., 41.]]])

In [6]:
W = torch.zeros((5, 5))
W[range(5), range(5)] = 2.0
W[range(4), range(1, 5)] = -1.0
W[range(1, 5), range(4)] = 1.0

In [7]:
W

tensor([[ 2., -1.,  0.,  0.,  0.],
        [ 1.,  2., -1.,  0.,  0.],
        [ 0.,  1.,  2., -1.,  0.],
        [ 0.,  0.,  1.,  2., -1.],
        [ 0.,  0.,  0.,  1.,  2.]])

In [8]:
W @ x.squeeze()

tensor([ 9., 20., 22., 24., 41.])

In [9]:
delta_x = torch.zeros_like(x)
delta_x[0, 0, 2] = 1.0

eps = 1e-2

In [10]:
(F.conv1d(x + eps*delta_x, w, padding=1) - F.conv1d(x - eps*delta_x, w, padding=1))/2/eps

tensor([[[ 0.0000, -1.0000,  2.0000,  1.0000,  0.0000]]])

In [11]:
W @ delta_x.squeeze()

tensor([ 0., -1.,  2.,  1.,  0.])

In [12]:
F.conv1d(delta_x, w, padding=1)

tensor([[[ 0., -1.,  2.,  1.,  0.]]])

In [13]:
F.conv_transpose1d(delta_x, w.flip(2), padding=1)

tensor([[[ 0., -1.,  2.,  1.,  0.]]])

# The 2D case

In [26]:
W = torch.arange(9.0).reshape(1, 1, 3, 3)
x = 10 * torch.arange(25.0).reshape(1, 5, 5)

delta_x = torch.zeros_like(x)
delta_x[0, 2, 2] = 1.0

eps = 1e-3

In [30]:
(F.conv2d(x + eps*delta_x, W, padding=0) - F.conv2d(x - eps*delta_x, W, padding=0))/2/eps

tensor([[[7.8125, 7.0801, 6.1035],
         [4.8828, 3.9062, 2.9297],
         [1.9531, 0.9766, 0.0000]]])

In [31]:
F.conv_transpose2d(delta_x, W.flip(2).flip(3), padding=0)

tensor([[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 8., 7., 6., 0., 0.],
         [0., 0., 5., 4., 3., 0., 0.],
         [0., 0., 2., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]])

In [32]:
F.conv2d(delta_x, W, padding=0)

tensor([[[8., 7., 6.],
         [5., 4., 3.],
         [2., 1., 0.]]])